const Cities = Object.freeze({
  Alexandria: "alexandria",
  Matrouh: "matrouh",
  Beheira: "beheira",
  Cairo: "cairo",
  KafrElSheikh: "kafr elsheikh",
  Damietta: "damietta",
  Giza: "giza",
  Qalyubia: "qalyubia",
  PortSaid: "portsaid",
  Suez: "suez",
  Dakahlia: "dakahlia",
  Sharqia: "sharqia",
  Gharbia: "gharbia",
  Monufia: "monufia",
  Ismailia: "ismailia",
  BeniSuef: "benisuef",
  Faiyum: "faiyum",
  Minya: "minya",
  Asyut: "asyut",
  Sohag: "sohag",
  Qena: "qena",
  Aswan: "aswan",
  Luxor: "luxor",
  RedSea: "redsea",
  NewValley: "newvalley",
  NorthSinai: "northsinai",
  SouthSinai: "southsinai",
});

module.exports = Cities;
